networks:
  maintenance:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: yurii.bondar
      POSTGRES_PASSWORD: strong#999
    volumes:
      - /home/yurii/db-storage/sql/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - maintenance

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: yurii.bondar
      MONGO_INITDB_ROOT_PASSWORD: strong#999
    volumes:
      - /home/yurii/db-storage/no-sql/mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      - maintenance

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - maintenance

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      - maintenance
